server:
  port: 8082

spring:
  application:
    name: farm-listing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/farm_rental_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
